### ISSUE TITLE
General Usage documentation

### ISSUE THREAD

**Issue by ashiklom** [openscm/openscm-twolayermodel#17]
On the [General Usage](https://openscm-two-layer-model.readthedocs.io/en/latest/usage.html) page of the documentation, it would be useful to add a hyperlink to the notebooks directory of the repository (since GitHub does a nice job of rendering the notebooks).

Also / Alternatively, you might consider rendering the notebooks within the ReadTheDocs documentation -- it seems like it should be possible to do this automatically with [`nbsphinx`](https://nbsphinx.readthedocs.io/en/0.8.0/usage.html#Automatic-Creation-of-HTML-and-PDF-output-on-readthedocs.org), but I've never actually tried it.

(Opened as part of https://github.com/openjournals/joss-reviews/issues/2766).

**Comment by znicholls** [comment]
Great suggestion thanks. I've done it, it means the notebooks move to a slightly less obvious place but the documentation is more complete so I think a good tradeoff?

**Comment by ashiklom** [comment]
Rendered notebooks look great! Seems like a fine trade-off to me, as long as the links to the notebooks are up to date everywhere.
