### ISSUE TITLE
Run arrays of two-layer model parameters

### ISSUE THREAD

**Issue by chrisroadmap** [openscm/openscm-twolayermodel#19]
Currently openscm-twolayermodel can run arrays of scenarios (of different emissions) given the same two-layer model parameters. This is quick. It would be great to do the opposite - run one emissions scenario with different two-layer parameters, without using a for loop and then appending the results, which is slow.  Option could be either to allow `runner.du`, `runner.dl` etc be arrays, or allow parameters to be passed in a twolayer-model `ScmRun` instance along with the emissions to drive the model.

**Comment by znicholls** [comment]
Given all the parallel infrastructure in https://github.com/openscm/openscm-runner, it might be best to put this functionality there?

**Comment by chrisroadmap** [comment]
Sure - let's add to that wishlist and close this.
